import { Level } from './types';

export const LEVELS: Level[] = [
  {
    id: 1,
    nameKey: "cola",
    bottleColor: "bg-[#2b1108]",
    bubbleColor: "bg-white/40",
    targetScore: 20,
    spawnRate: 800,
    speedRange: [6, 10]
  },
  {
    id: 2,
    nameKey: "lime",
    bottleColor: "bg-[#1d4d1d]",
    bubbleColor: "bg-[#ccffcc]/50",
    targetScore: 40,
    spawnRate: 600,
    speedRange: [5, 8]
  },
  {
    id: 3,
    nameKey: "orange",
    bottleColor: "bg-[#e67e22]",
    bubbleColor: "bg-[#f1c40f]/60",
    targetScore: 70,
    spawnRate: 450,
    speedRange: [4, 7]
  },
  {
    id: 4,
    nameKey: "grape",
    bottleColor: "bg-[#4a148c]",
    bubbleColor: "bg-[#e1bee7]/50",
    targetScore: 110,
    spawnRate: 350,
    speedRange: [3, 6]
  },
  {
    id: 5,
    nameKey: "soda",
    bottleColor: "bg-[#01579b]",
    bubbleColor: "bg-[#b3e5fc]/60",
    targetScore: 160,
    spawnRate: 250,
    speedRange: [2, 5]
  }
];

export const I18N = {
  en: {
    title: "FIZZY POP",
    start: "Start Game",
    pause: "Paused",
    resume: "Resume",
    reset: "Reset Game",
    gameOver: "POPPED!",
    score: "Score",
    highScore: "High Score",
    level: "Level",
    target: "Target",
    nextLevel: "Level Up!",
    nextDesc: "Preparing fresh pour...",
    tryAgain: "Try Again",
    feedback: "Feedback",
    searchPlaceholder: "Search flavors...",
    cola: "Classic Cola",
    lime: "Lemon Lime",
    orange: "Sparkling Orange",
    grape: "Purple Grape",
    soda: "Blue Soda Water",
    lang: "English",
    gameSpeed: "Game Speed",
    instruction: "Inside a fizzy bottle! Pop bubbles to the beat.",
    export: "Export Stats",
    clear: "Clear",
    settings: "Settings",
    volume: "Volume",
    master: "Master",
    music: "Music",
    sfx: "SFX",
    musicTrack: "Music Track",
    trackPopcorn: "Classic Popcorn",
    trackTechno: "Techno Vibes",
    trackRetro: "Retro Arcade",
    trackNone: "None"
  },
  he: {
    title: "FIZZY POP",
    start: "התחל לשחק",
    pause: "הפסקה",
    resume: "המשך",
    reset: "איפוס משחק",
    gameOver: "POPPED!",
    score: "ניקוד",
    highScore: "שיא",
    level: "שלב",
    target: "יעד",
    nextLevel: "שלב הבא!",
    nextDesc: "מתכונן למזיגה חדשה...",
    tryAgain: "נסה שוב",
    feedback: "משוב",
    searchPlaceholder: "חפש טעמים...",
    cola: "קולה קלאסית",
    lime: "לימון ליים",
    orange: "תפוז מוגז",
    grape: "ענבים סגולים",
    soda: "מי סודה כחולים",
    lang: "עברית",
    gameSpeed: "מהירות משחק",
    instruction: "אתה בתוך בקבוק! פוצץ בועות לקצב.",
    export: "ייצוא נתונים",
    clear: "נקה",
    settings: "הגדרות",
    volume: "עוצמת שמע",
    master: "ראשי",
    music: "מוזיקה",
    sfx: "אפקטים",
    musicTrack: "רצועת מוזיקה",
    trackPopcorn: "פופקורן קלאסי",
    trackTechno: "טכנו מודרני",
    trackRetro: "ארקייד רטרו",
    trackNone: "ללא מוזיקה"
  },
  zh: {
    title: "气泡消除",
    start: "开始游戏",
    pause: "暂停",
    resume: "继续",
    reset: "重置游戏",
    gameOver: "游戏结束",
    score: "分数",
    highScore: "最高分",
    level: "等级",
    target: "目标",
    nextLevel: "升级！",
    nextDesc: "准备中...",
    tryAgain: "再试一次",
    feedback: "反馈",
    searchPlaceholder: "搜索口味...",
    cola: "经典可乐",
    lime: "柠檬莱姆",
    orange: "香橙汽水",
    grape: "紫葡萄",
    soda: "蓝色苏打水",
    lang: "中文",
    gameSpeed: "游戏速度",
    instruction: "在汽水瓶里！跟随节拍消除气泡。",
    export: "导出统计",
    clear: "清除",
    settings: "设置",
    volume: "音量",
    master: "主音量",
    music: "音乐",
    sfx: "音效",
    musicTrack: "背景音乐",
    trackPopcorn: "经典爆米花",
    trackTechno: "电子律动",
    trackRetro: "复古街机",
    trackNone: "关闭音乐"
  },
  hi: {
    title: "फ़िज़ी पॉप",
    start: "शुरू करें",
    pause: "रुका हुआ",
    resume: "जारी रखें",
    reset: "रीसेट",
    gameOver: "खेल खत्म!",
    score: "स्कोर",
    highScore: "उच्च स्कोर",
    level: "स्तर",
    target: "लक्ष्य",
    nextLevel: "स्तर ऊपर!",
    nextDesc: "तैयारी हो रही है...",
    tryAgain: "पुनः प्रयास",
    feedback: "प्रतिक्रिया",
    searchPlaceholder: "स्वाद खोजें...",
    cola: "कोला",
    lime: "नींबू",
    orange: "संतरा",
    grape: "अंगूर",
    soda: "सोडा",
    lang: "हिन्दी",
    gameSpeed: "गति",
    instruction: "बोतल के अंदर! बुलबुले फोड़ें।",
    export: "निर्यात",
    clear: "साफ करें",
    settings: "सेटिंग्स",
    volume: "आवाज़",
    master: "मास्टर",
    music: "संगीत",
    sfx: "प्रभाव",
    musicTrack: "संगीत ट्रैक",
    trackPopcorn: "क्लासिक पॉपकॉर्न",
    trackTechno: "टेक्नो",
    trackRetro: "रेट्रो",
    trackNone: "कोई नहीं"
  },
  de: {
    title: "FIZZY POP",
    start: "Starten",
    pause: "Pause",
    resume: "Weiter",
    reset: "Zurücksetzen",
    gameOver: "GEPLATZT!",
    score: "Punkte",
    highScore: "Bestleistung",
    level: "Level",
    target: "Ziel",
    nextLevel: "Level Up!",
    nextDesc: "Wird vorbereitet...",
    tryAgain: "Nochmal",
    feedback: "Feedback",
    searchPlaceholder: "Aromen suchen...",
    cola: "Cola",
    lime: "Limette",
    orange: "Orange",
    grape: "Traube",
    soda: "Soda",
    lang: "Deutsch",
    gameSpeed: "Tempo",
    instruction: "In der Flasche! Blasen zum Takt platzen lassen.",
    export: "Exportieren",
    clear: "Löschen",
    settings: "Einstellungen",
    volume: "Lautstärke",
    master: "Gesamt",
    music: "Musik",
    sfx: "SFX",
    musicTrack: "Musikstück",
    trackPopcorn: "Popcorn Klassik",
    trackTechno: "Techno-Beats",
    trackRetro: "Retro-Arcade",
    trackNone: "Aus"
  },
  es: {
    title: "FIZZY POP",
    start: "Empezar",
    pause: "Pausa",
    resume: "Continuar",
    reset: "Reiniciar",
    gameOver: "¡BOOM!",
    score: "Puntos",
    highScore: "Record",
    level: "Nivel",
    target: "Objetivo",
    nextLevel: "¡Nivel más!",
    nextDesc: "Preparando...",
    tryAgain: "Otra vez",
    feedback: "Comentarios",
    searchPlaceholder: "Buscar sabores...",
    cola: "Cola",
    lime: "Lima",
    orange: "Naranja",
    grape: "Uva",
    soda: "Soda",
    lang: "Español",
    gameSpeed: "Velocidad",
    instruction: "¡En la botella! Explota burbujas.",
    export: "Exportar",
    clear: "Limpiar",
    settings: "Ajustes",
    volume: "Volumen",
    master: "Maestro",
    music: "Música",
    sfx: "Efectos",
    musicTrack: "Canción",
    trackPopcorn: "Popcorn Clásico",
    trackTechno: "Energía Techno",
    trackRetro: "Arcade Retro",
    trackNone: "Ninguna"
  },
  fr: {
    title: "FIZZY POP",
    start: "Jouer",
    pause: "Pause",
    resume: "Continuer",
    reset: "Réinitialiser",
    gameOver: "PERDU !",
    score: "Score",
    highScore: "Record",
    level: "Niveau",
    target: "Objectif",
    nextLevel: "Niveau Up!",
    nextDesc: "Préparation...",
    tryAgain: "Réessayer",
    feedback: "Avis",
    searchPlaceholder: "Saveurs...",
    cola: "Cola",
    lime: "Citron",
    orange: "Orange",
    grape: "Raisin",
    soda: "Soda",
    lang: "Français",
    gameSpeed: "Vitesse",
    instruction: "Dans la bouteille ! Éclatez les bulles.",
    export: "Exporter",
    clear: "Effacer",
    settings: "Réglages",
    volume: "Volume",
    master: "Principal",
    music: "Musique",
    sfx: "Effets",
    musicTrack: "Musique",
    trackPopcorn: "Popcorn Classique",
    trackTechno: "Vibes Techno",
    trackRetro: "Rétro Arcade",
    trackNone: "Aucune"
  }
};