
import { Level } from './types';

export const LEVELS: Level[] = [
  {
    id: 1,
    nameKey: "cola",
    bottleColor: "bg-[#2b1108]",
    bubbleColor: "bg-white/40",
    targetScore: 20,
    spawnRate: 800,
    speedRange: [6, 10]
  },
  {
    id: 2,
    nameKey: "lime",
    bottleColor: "bg-[#1d4d1d]",
    bubbleColor: "bg-[#ccffcc]/50",
    targetScore: 40,
    spawnRate: 600,
    speedRange: [5, 8]
  },
  {
    id: 3,
    nameKey: "orange",
    bottleColor: "bg-[#e67e22]",
    bubbleColor: "bg-[#f1c40f]/60",
    targetScore: 70,
    spawnRate: 450,
    speedRange: [4, 7]
  },
  {
    id: 4,
    nameKey: "grape",
    bottleColor: "bg-[#4a148c]",
    bubbleColor: "bg-[#e1bee7]/50",
    targetScore: 110,
    spawnRate: 350,
    speedRange: [3, 6]
  },
  {
    id: 5,
    nameKey: "soda",
    bottleColor: "bg-[#01579b]",
    bubbleColor: "bg-[#b3e5fc]/60",
    targetScore: 160,
    spawnRate: 250,
    speedRange: [2, 5]
  }
];

export const I18N = {
  en: {
    title: "FIZZY POP",
    start: "Start Game",
    pause: "Paused",
    resume: "Resume",
    reset: "Reset Game",
    gameOver: "POPPED!",
    score: "Score",
    highScore: "High Score",
    level: "Level",
    target: "Target",
    nextLevel: "Level Up!",
    nextDesc: "Preparing fresh pour...",
    tryAgain: "Try Again",
    feedback: "Send Feedback",
    searchPlaceholder: "Search drink flavors...",
    cola: "Classic Cola",
    lime: "Lemon Lime",
    orange: "Sparkling Orange",
    grape: "Purple Grape",
    soda: "Blue Soda Water",
    lang: "English",
    gameSpeed: "Game Speed",
    instruction: "You are inside a fizzy drink bottle! Pop bubbles to the beat. Golden ones are worth more!"
  },
  he: {
    title: "FIZZY POP",
    start: "התחל לשחק",
    pause: "הפסקה",
    resume: "המשך",
    reset: "איפוס משחק",
    gameOver: "POPPED!",
    score: "ניקוד",
    highScore: "שיא",
    level: "שלב",
    target: "יעד",
    nextLevel: "שלב הבא!",
    nextDesc: "מתכונן למזיגה חדשה...",
    tryAgain: "נסה שוב",
    feedback: "שלח משוב",
    searchPlaceholder: "חפש טעמי שתייה...",
    cola: "קולה קלאסית",
    lime: "לימון ליים",
    orange: "תפוז מוגז",
    grape: "ענבים סגולים",
    soda: "מי סודה כחולים",
    lang: "עברית",
    gameSpeed: "מהירות משחק",
    instruction: "אתה בתוך בקבוק משקה מוגז! פוצץ בועות לקצב ה'פופקורן'. בועות זהב שוות יותר!"
  },
  zh: {
    title: "气泡消除",
    start: "开始游戏",
    pause: "暂停",
    resume: "继续",
    reset: "重置游戏",
    gameOver: "爆裂！",
    score: "分数",
    highScore: "最高分",
    level: "等级",
    target: "目标",
    nextLevel: "升级！",
    nextDesc: "准备新鲜倾倒...",
    tryAgain: "再试一次",
    feedback: "发送反馈",
    searchPlaceholder: "搜索饮料口味...",
    cola: "经典可乐",
    lime: "柠檬莱姆",
    orange: "香橙汽水",
    grape: "紫葡萄",
    soda: "蓝色苏打水",
    lang: "中文",
    gameSpeed: "游戏速度",
    instruction: "你在一个汽水瓶里！跟随节拍消除气泡。金色的气泡更值钱！"
  },
  hi: {
    title: "फ़िज़ी पॉप",
    start: "खेल शुरू करें",
    pause: "रुका हुआ",
    resume: "जारी रखें",
    reset: "खेल रीसेट करें",
    gameOver: "पॉप्ड!",
    score: "स्कोर",
    highScore: "उच्च स्कोर",
    level: "स्तर",
    target: "लक्ष्य",
    nextLevel: "स्तर ऊपर!",
    nextDesc: "ताज़ा डालने की तैयारी...",
    tryAgain: "पुनः प्रयास करें",
    feedback: "प्रतिक्रिया भेजें",
    searchPlaceholder: "ड्रिंक फ्लेवर खोजें...",
    cola: "क्लासिक कोला",
    lime: "नींबू चूना",
    orange: "स्पार्कलिंग ऑरेंज",
    grape: "बैंगनी अंगूर",
    soda: "नीला सोडा पानी",
    lang: "हिन्दी",
    gameSpeed: "खेल की गति",
    instruction: "आप फ़िज़ी ड्रिंक की बोतल के अंदर हैं! ताल पर बुलबुले फोड़ें। सुनहरे बुलबुले ज़्यादा कीमती हैं!"
  },
  de: {
    title: "FIZZY POP",
    start: "Spiel starten",
    pause: "Pause",
    resume: "Fortsetzen",
    reset: "Spiel zurücksetzen",
    gameOver: "GEPLATZT!",
    score: "Punktzahl",
    highScore: "Bestleistung",
    level: "Ebene",
    target: "Ziel",
    nextLevel: "Level Aufstieg!",
    nextDesc: "Frisches Gießen wird vorbereitet...",
    tryAgain: "Nochmal versuchen",
    feedback: "Feedback senden",
    searchPlaceholder: "Getränkearomen suchen...",
    cola: "Klassische Cola",
    lime: "Zitrone Limette",
    orange: "Prickelnde Orange",
    grape: "Lila Traube",
    soda: "Blaues Sodawasser",
    lang: "Deutsch",
    gameSpeed: "Spielgeschwindigkeit",
    instruction: "Du bist in einer Sprudelflasche! Lass Blasen zum Takt platzen. Goldene sind mehr wert!"
  },
  es: {
    title: "FIZZY POP",
    start: "Empezar juego",
    pause: "Pausado",
    resume: "Reanudar",
    reset: "Reiniciar juego",
    gameOver: "¡EXPLOTÓ!",
    score: "Puntuación",
    highScore: "Record",
    level: "Nivel",
    target: "Objetivo",
    nextLevel: "¡Nivel superado!",
    nextDesc: "Preparando vertido fresco...",
    tryAgain: "Intentar de nuevo",
    feedback: "Enviar comentarios",
    searchPlaceholder: "Buscar sabores...",
    cola: "Cola clásica",
    lime: "Limón Lima",
    orange: "Naranja gaseosa",
    grape: "Uva morada",
    soda: "Sifón azul",
    lang: "Español",
    gameSpeed: "Velocidad del juego",
    instruction: "¡Estás dentro de una botella de refresco! Explota burbujas al ritmo. ¡Las doradas valen más!"
  },
  fr: {
    title: "FIZZY POP",
    start: "Démarrer",
    pause: "Pause",
    resume: "Reprendre",
    reset: "Réinitialiser",
    gameOver: "ÉCLATÉ !",
    score: "Score",
    highScore: "Record",
    level: "Niveau",
    target: "Objectif",
    nextLevel: "Niveau supérieur !",
    nextDesc: "Préparation du service...",
    tryAgain: "Réessayer",
    feedback: "Envoyer un avis",
    searchPlaceholder: "Rechercher des saveurs...",
    cola: "Cola classique",
    lime: "Citron Lime",
    orange: "Orange pétillante",
    grape: "Raisin violet",
    soda: "Eau gazeuse bleue",
    lang: "Français",
    gameSpeed: "Vitesse du jeu",
    instruction: "Vous êtes dans une bouteille de soda ! Éclatez les bulles en rythme. Les dorées valent plus !"
  }
};
